TAJIDUO_BASE_URL = "https://bbs-api.tajiduo.com"
TAJIDUO_USER_CENTER_APP_ID = "10551"
TAJIDUO_APP_VERSION = "1.2.4"
TAJIDUO_CLIENT_UID = "0"
TAJIDUO_DS_SALT = "pUds3dfMkl"
TAJIDUO_DS_NONCE_ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"
TAJIDUO_USER_AGENT = "okhttp/4.12.0"

# Games
GAME_ID_YIHUAN = "1289"
GAME_ID_HUANTA = "1256"

# Sign-in community
TAJIDUO_SIGNIN_COMMUNITY_ID = "2"
YIHUAN_TASK_COMMUNITY_IDS = ["1", "2"]

# Task keys
TASK_KEY_BROWSE_POST = "browse_post_c"
TASK_KEY_LIKE_POST = "like_post_c"
TASK_KEY_SHARE = "share"

# Laohu
LAOHU_BASE_URL = "https://user.laohu.com"
LAOHU_APP_ID = 10550
LAOHU_APP_KEY = "89155cc4e8634ec5b1b6364013b23e3e"
LAOHU_SDK_VERSION = "4.273.0"
LAOHU_USER_AGENT = "okhttp/4.9.0"
LAOHU_DEFAULT_PACKAGE = "com.pwrd.htassistant"
LAOHU_DEFAULT_VERSION_CODE = 12

# Share platform
SHARE_PLATFORM_WX_SESSION = "6"
